//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicMathAddIn.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAEAAAD/////AQAAAAAAAAAMAgAAAFFCYXNpY01hdGhBZGRJbiwgVmVyc2lvbj0xLjAuMC4wLCBDdWx0d" +
            "XJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWY3ZDI3M2ZlZjc0NGQ0MTMFAQAAACJCYXNpY01hdGhBZ" +
            "GRJbi5NYXRoU2V0dGluZ3NNYW5hZ2VyBAAAAAdWZXJzaW9uCENvbXBhcmVyCEhhc2hTaXplDUtleVZhb" +
            "HVlUGFpcnMAAwADCJIBU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuR2VuZXJpY0VxdWFsaXR5Q29tc" +
            "GFyZXJgMVtbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZ" +
            "XV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0I+gFTeXN0ZW0uQ29sbGVjdGlvb" +
            "nMuR2VuZXJpYy5LZXlWYWx1ZVBhaXJgMltbU3lzdGVtLlN0cmluZywgbXNjb3JsaWIsIFZlcnNpb249N" +
            "C4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XSxbQ" +
            "mFzaWNNYXRoQWRkSW4uTWF0aFNldHRpbmdzLCBCYXNpY01hdGhBZGRJbiwgVmVyc2lvbj0xLjAuMC4wL" +
            "CBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWY3ZDI3M2ZlZjc0NGQ0MTNdXVtdAgAAAAUAA" +
            "AAJAwAAAAMAAAAJBAAAAAQDAAAAkgFTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5HZW5lcmljRXF1Y" +
            "WxpdHlDb21wYXJlcmAxW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDd" +
            "Wx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQAAAAAHBAAAAAABA" +
            "AAAAQAAAAP4AVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlUGFpcmAyW1tTeXN0ZW0uU" +
            "3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tle" +
            "VRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtCYXNpY01hdGhBZGRJbi5NYXRoU2V0dGluZ3MsIEJhc2ljT" +
            "WF0aEFkZEluLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Z" +
            "jdkMjczZmVmNzQ0ZDQxM11dBPv////4AVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleVZhbHVlU" +
            "GFpcmAyW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ld" +
            "XRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldLFtCYXNpY01hdGhBZGRJbi5NYXRoU" +
            "2V0dGluZ3MsIEJhc2ljTWF0aEFkZEluLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgU" +
            "HVibGljS2V5VG9rZW49ZjdkMjczZmVmNzQ0ZDQxM11dAgAAAANrZXkFdmFsdWUBBBtCYXNpY01hdGhBZ" +
            "GRJbi5NYXRoU2V0dGluZ3MCAAAABgYAAAAG6buY6K6kCQcAAAAFBwAAABtCYXNpY01hdGhBZGRJbi5NY" +
            "XRoU2V0dGluZ3MOAAAABVBhZ2VzBE1vZGUDQWRkA1N1YgNNdWwDRGl2BE1heEEETWluQQRNYXhTBE1pb" +
            "lMETWF4TQRNaW5NBE1heEQETWluRAEAAAAAAAEBAQEBAQEBCAEBAQECAAAABggAAAABMQAAAAABAAAAB" +
            "gkAAAACMTAGCgAAAAEzBgsAAAACMTAGDAAAAAE1Bg0AAAABOQYOAAAAATIGDwAAAAE5BhAAAAABMgs=")]
        public string Prefs {
            get {
                return ((string)(this["Prefs"]));
            }
            set {
                this["Prefs"] = value;
            }
        }
    }
}
